-- Test timeline events for alternating layout verification
-- Insert sample events to test the alternating timeline layout

INSERT INTO life_events (
  id,
  user_id,
  title,
  description,
  start_date,
  end_date,
  is_ongoing,
  category,
  location,
  importance,
  tags,
  metadata,
  created_at,
  updated_at
) VALUES
  (
    gen_random_uuid(),
    auth.uid(),
    'First Day of School',
    'Started kindergarten at Lincoln Elementary. Met my best friend Sarah.',
    '1995-09-01'::date,
    NULL,
    false,
    'education',
    'New York, NY',
    7,
    ARRAY['school', 'childhood', 'friends'],
    '{}',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    auth.uid(),
    'Learned to Ride a Bike',
    'Finally mastered riding without training wheels in the park.',
    '1996-06-15'::date,
    NULL,
    false,
    'personal',
    'Central Park, NY',
    8,
    ARRAY['achievement', 'childhood'],
    '{}',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    auth.uid(),
    'Family Vacation to Disney World',
    'Amazing week-long trip to Orlando. Rode Space Mountain for the first time.',
    '1997-07-10'::date,
    '1997-07-17'::date,
    false,
    'travel',
    'Orlando, FL',
    9,
    ARRAY['family', 'vacation', 'travel'],
    '{}',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    auth.uid(),
    'Won Science Fair',
    'First place in the school science fair with volcano project.',
    '1998-05-20'::date,
    NULL,
    false,
    'achievement',
    'Lincoln Elementary',
    8,
    ARRAY['science', 'achievement', 'school'],
    '{}',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    auth.uid(),
    'Started High School',
    'Began freshman year at Roosevelt High School. Nervous but excited.',
    '2001-09-03'::date,
    NULL,
    false,
    'education',
    'New York, NY',
    7,
    ARRAY['school', 'milestone'],
    '{}',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    auth.uid(),
    'Got Driver''s License',
    'Passed both written and driving tests on first try!',
    '2003-07-28'::date,
    NULL,
    false,
    'milestone',
    'NY DMV',
    9,
    ARRAY['independence', 'milestone'],
    '{}',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    auth.uid(),
    'Graduated High School',
    'Valedictorian speech and college-bound. So proud of this achievement.',
    '2005-06-15'::date,
    NULL,
    false,
    'achievement',
    'Roosevelt High School',
    10,
    ARRAY['graduation', 'achievement', 'milestone'],
    '{}',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    auth.uid(),
    'Started College',
    'First day at NYU studying Computer Science. New chapter begins!',
    '2005-09-01'::date,
    NULL,
    false,
    'education',
    'New York University',
    8,
    ARRAY['college', 'education', 'computer-science'],
    '{}',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    auth.uid(),
    'First Job',
    'Software Developer intern at a startup. Learning so much!',
    '2008-06-01'::date,
    '2008-08-31'::date,
    false,
    'career',
    'Manhattan, NY',
    8,
    ARRAY['career', 'internship', 'programming'],
    '{}',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    auth.uid(),
    'College Graduation',
    'Bachelor''s degree in Computer Science. Ready for the real world!',
    '2009-05-20'::date,
    NULL,
    false,
    'achievement',
    'New York University',
    10,
    ARRAY['graduation', 'achievement', 'milestone'],
    '{}',
    now(),
    now()
  );
